const users = [
  {
    id: 1,
    userId: "user1",
    name: "Branch User 1",
    email: "bu1@ourbank.com",
    hasBranchAccess: true,
    hasAdminAccess: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    userId: "user2",
    name: "Branch User 2",
    email: "bu2@ourbank.com",
    hasBranchAccess: true,
    hasAdminAccess: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    userId: "user3",
    name: "Branch User 3",
    email: "bu3@ourbank.com",
    hasBranchAccess: true,
    hasAdminAccess: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    userId: "user4",
    name: "Branch User 4",
    email: "bu4@ourbank.com",
    hasBranchAccess: true,
    hasAdminAccess: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    userId: "admin",
    name: "Administrator",
    email: "admin@ourbank.com",
    hasBranchAccess: true,
    hasAdminAccess: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = users;
